name: alpr_watchlist
description: Application ALPR (Automatic License Plate Recognition) avec watchlist et navigation HERE Maps

# Version de l'application
version: 1.0.0+6

# Configuration de l'environnement
environment:
  sdk: '>=3.5.0 <4.0.0'

# Dépendances
dependencies:
  flutter:
    sdk: flutter

  # HERE SDK pour la navigation
  here_sdk:
    path: plugins/here_sdk

  # Vision et caméra pour l'ALPR
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0

  # Localisation et navigation
  geolocator: ^10.1.0
  location: ^7.0.0

  # Permissions
  permission_handler: ^11.0.0

  # Stockage et persistance
  shared_preferences: ^2.3.4
  path_provider: ^2.1.4

  # Notifications
  awesome_notifications: ^0.8.2

  # Interface utilisateur
  cupertino_icons: ^1.0.5

  # HTTP et réseau
  http: ^1.1.0

  # Utilitaires
  intl: ^0.19.0

  # Cartes de fallback (si HERE Maps ne fonctionne pas)
  flutter_map: ^6.1.0
  latlong2: ^0.8.1

# Dépendances de développement
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Configuration Flutter
flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/sounds/

  # Polices personnalisées (optionnel)
  # fonts:
  #   - family: RobotoMono
  #     fonts:
  #       - asset: fonts/RobotoMono-Regular.ttf
  #       - asset: fonts/RobotoMono-Bold.ttf
  #         weight: 700

# Configuration spécifique à l'application
# Ne pas publier sur pub.dev
publish_to: 'none'

# Métadonnées
author: VikingProduction
homepage: https://github.com/VikingProduction/alpdr
