name: alpr_watchlist
description: Scan plaques d'immatriculation (OCR) en flux vidéo + alerte watchlist + navigation HERE Maps
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  # ALPR existant
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.3.4
  
  # Navigation HERE Maps + Radar
  here_sdk: ^4.17.0
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  awesome_notifications: ^0.8.2
  http: ^1.1.0
  
  # UI/UX
  flutter_map: ^6.1.0  # Backup si HERE pose problème
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/  # Sons d'alertes radar
