name: alpr_watchlist
description: Scan plaques d’immatriculation (OCR) en flux vidéo + alerte watchlist (Android/iOS)
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.11.0
  google_mlkit_text_recognition: ^0.15.0
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
